### ISSUE TITLE
Regarding scheduling this task

### ISSUE THREAD

**Issue by jciallella** [JustinLloyd/chia-utilities#1]
Hi Justin! Thank you for creating this utility. I use it everyday and very much like it.

I read that you automate running this task with scheduler, but I've found that my setup is not functioning properly. This forces me to do the running manually, but if I forget even once, it creates a huge back-up. 

Could you please (and thank you in advance) suggest how to set it up in the scheduler so it runs automatically like yours?  Again thank you so much.

- Jack

**Comment by JustinLloyd** [comment]
`schedule_plotter_tasks.ps1`
